[package]
name = "zox"
version = "0.1.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"

[dependencies]
csv = "1.1"
serde = { version = "1", features = ["derive"] }
pico-args = "0.3.0"
home = "0.5.1"
main_error = "0.1.0"